sudo: required
services:
  - docker

language: bash

before_install:
  - docker pull mysql:5.6
  - docker run -d -e "MYSQL_ROOT_PASSWORD=verysecret" --name mysqldb1 mysql:5.6 
  - docker ps -a
  - docker build -t realworld/docker-radius .
  - docker run -d -p 0.0.0.0:1812:1812/udp -p 0.0.0.0:1813:1813/udp --link mysqldb1:mysql -e "MYSQL_ROOT_PASSWORD=verysecret" --name radius1 realworld/docker-radius
  - docker ps -a
  - apt-get update -qq
  - apt-get install -y freeradius-utils

script:
  - sleep 30
  - docker exec "radius1" /bin/bash /usr/src/build/test-radius.sh
  - docker exec "radius1" /bin/bash /usr/src/build/load-test-data.sh
  - docker exec "radius1" radtest test@testing.com testing123 127.0.0.1 0 testing123
  - radtest test@testing.com testing123 127.0.0.1 0 password

after_success:
  - curl -X POST https://registry.hub.docker.com/u/realworld/radius/trigger/$DOCKERHUB_ID/

