sudo: required
services:
  - docker

environment:
  MYSQL_ROOT_PASSWORD: verysecret

before_install:
  - docker pull mysql:5.6
  - docker run -d -e "MYSQL_ROOT_PASSWORD=verysecret" --name mysqldb1 mysql:5.6 
  - docker ps -a
  - docker build -t realworld/docker-radius .

script:
  - docker run --link mysqldb1:mysql -e "MYSQL_ROOT_PASSWORD=verysecret" realworld/docker-radius /bin/bash /usr/src/build/test-radius.sh